[env:m5stick-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.arduino.partitions = default_8MB.csv

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_MODE=1

lib_deps = 
    m5stack/M5Unified@^0.1.0
    bblanchon/ArduinoJson@^6.21.3
